import './globals.css'
import { Inter } from 'next/font/google'
import { Header } from '@/useable/Header'
import { Foot } from '@/useable/Foot'
import Providers from '@/compo/Provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <Header/>
        {children}
        <Foot/>
        </Providers>
        </body>
    </html>
  )
}
